exclude:
  - /bin/.*
  - /lib/.*
  - /weblogger-docs/devguide/.*
  - /weblogger-docs/examples/configs/.*
  - /weblogger-docs/examples/macros/.*
  - /weblogger-docs/examples/rollertask/.*
  - /weblogger-docs/examples/scripting/bsf/lib/.*
  - /weblogger-docs/examples/scripting/groovy/examples/.*
  - /weblogger-docs/installguide/.*
  - /weblogger-docs/templateguide/.*
  - /weblogger-docs/testing/.*
  - /weblogger-docs/userguide/.*
include:
  - /planet-business/src/.*
  - /planet-web/src/.*
  - /roller-core/src/.*
  - /test-utils/src/.*
  - /weblogger-assembly/src/.*
  - /weblogger-business/src/.*
  - /weblogger-docs/examples/plugins/pluginmodel/src/.*
  - /weblogger-docs/examples/scripting/bsf/src/.*
  - /weblogger-docs/examples/scripting/groovy/src/.*
  - /weblogger-docs/examples/scripting/groovy/src/.*
  - /weblogger-war-assembly/src/.*
  - /weblogger-web/src/.*
  - /weblogger-webapp/src/.*
